### PR TITLE
feat: add `maxAge` option for Cache-Control HTTP response header

### PR DESCRIPTION
**Pull request by candidosales**
- [x] Replaced `babel-parser` (deprecated) with `@babel/eslint-parser`;
- [x] Added a new option config to set the Cache-Control  HTTP response header;
- [x] Added config validation using `yup`;
- [x] Updated documentation, including `maxAge` instructions;
- [x] Upgrade version `1.5.0` in `package.json`;

Issue: https://github.com/strapi-community/strapi-plugin-local-image-sharp/issues/19

### CODE REVIEW

**Comment by candidosales** [comment]
@stafyniaksacha , I made a PR. Could you review it and test it? https://github.com/strapi-community/strapi-plugin-local-image-sharp/pull/20

**Comment by stafyniaksacha** [comment]
Hello @candidosalesn, tahnks for your contribution! can you run `yarn run eslint:fix` on your branch ?

**Comment by candidosales** [comment]
@stafyniaksacha, what's your `babel-eslint` version installed globally in your machine and Node version? I installed it as `devDependency`and I'm receiving those errors. Could you help me?

Node version: `v16.17.0`
`babel-eslint`: `"^10.1.0"`

```bash

/Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/playground/config/admin.js
  0:0  error  Parsing error: require() of ES Module /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

/Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/playground/config/api.js
  0:0  error  Parsing error: require() of ES Module /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

/Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/playground/config/database.js
  0:0  error  Parsing error: require() of ES Module /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

/Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/playground/config/middlewares.js
  0:0  error  Parsing error: require() of ES Module /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

/Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/playground/config/plugins.js
  0:0  error  Parsing error: require() of ES Module /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

/Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/playground/config/server.js
  0:0  error  Parsing error: require() of ES Module /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

/Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/playground/src/admin/app.example.js
  0:0  error  Parsing error: require() of ES Module /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

/Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/playground/src/admin/webpack.config.example.js
  0:0  error  Parsing error: require() of ES Module /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

/Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/playground/src/index.js
  0:0  error  Parsing error: require() of ES Module /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/eslint/node_modules/eslint-scope/lib/definition.js from /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js not supported.
Instead change the require of definition.js in /Users/candidosales/Documents/Projects/strapi-plugin-local-image-sharp/node_modules/babel-eslint/lib/require-from-eslint.js to a dynamic import() which is available in all CommonJS modules

```

**Comment by candidosales** [comment]
@stafyniaksacha, it's ready for the second review.

**Comment by candidosales** [comment]
Could you update the link on the ]Releases page](https://github.com/strapi-community/strapi-plugin-local-image-sharp/releases)?

The link is pointing to `https://github.com/strapi-community/strapi-plugin-rest-cache/blob/main/CHANGELOG.md`.

CleanShot 2023-02-27 at 22 35 31@2x

**Review by stafyniaksacha — APPROVED** [review]
Really great addition! Thanks for your contribution :)

**Comment by stafyniaksacha** [comment]
> * Upgrade version `1.5.0` in `package.json`;

Oops, didn't noticed this. Released as `1.6.0` as it's automatically bumped!

Also updated the changelog link, thanks for pointing it :)

**Comment by candidosales** [comment]
It's working! Thanks! 😄 

CleanShot 2023-02-28 at 09 42 43@2x

**Pull request merged**
